language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_script:
  - jackd -r -d dummy &
addons:
  apt:
    packages:
      - jackd
      - libjack-jackd2-dev
